# Test image mirroring the SBC boot path (u-boot -> extlinux -> kernel),
# but for qemu's `virt` machine. Uses modules/image/extlinux.nix, the
# same module the SBCs use. qemu provides u-boot via -bios, so this
# host has no firmware blobs in /boot - only the kernel/initrd/extlinux
# generated by modules/image/extlinux.nix.
{ ... }:

{
  imports = [
    ../modules/image/extlinux.nix
  ];

  image.repart.name = "mininix-vm-uboot";

  # Virtio devices exposed by qemu virt.
  boot.initrd.availableKernelModules = [
    "virtio_pci"
    "virtio_blk"
    "virtio_net"
    "virtio_scsi"
    "virtio_gpu"
  ];
  # Force-load virtio_gpu post-boot so /dev/dri/card0 is present when cage
  # starts. availableKernelModules is initrd-only.
  boot.kernelModules = [ "virtio_gpu" ];

  # Serial console on the virt machine.
  boot.kernelParams = [
    "console=ttyAMA0,115200n8"
    "console=tty0"
  ];
}
